print("Этапы развития человека")
print("Предшественники человека ?")
a=input()
print("Древнейшие люди?")
b=input()
print("Древние люди?")
c=input()
print("Люди современного типа?")
d=input()
print(a,b,c,d,sep="=>")
